spring:
  application:
    name: weather
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
    show-sql: true
  datasource: # 배포할때 RDS로 교체하기 위해 지우기
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      batch-size: 16384
      linger-ms: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.adjh.springbootkafka: DEBUG
    org:
      apache.kafka: INFO
      springframework.kafka: INFO

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration:
    accessToken: 10800000
    refreshToken: 1209600000

geo:
  access: ${GEO_KEY}
  secret: ${GEO_SECRET_KEY}